"""update

Revision ID: 1e27ceda7c2e
Revises: c207652104e8
Create Date: 2017-11-07 18:30:53.929855

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1e27ceda7c2e'
down_revision = 'c207652104e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
