"""init users table

Revision ID: 469c61a7fa6b
Revises: 9850a0a6e949
Create Date: 2017-11-07 15:09:08.419942

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '469c61a7fa6b'
down_revision = '9850a0a6e949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
