"""uniq constraint for user

Revision ID: 4953250f9122
Revises:
Create Date: 2017-11-07 15:25:44.680613

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4953250f9122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('salt', sa.BLOB(), nullable=True),
                    sa.Column('hash', sa.BLOB(), nullable=True),
                    sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('name'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
