"""uniq constraint for user

Revision ID: 65105ba2446d
Revises: 469c61a7fa6b
Create Date: 2017-11-07 15:22:46.837277

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '65105ba2446d'
down_revision = '469c61a7fa6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
