"""added notes table

Revision ID: 67257dca779e
Revises: 4953250f9122
Create Date: 2017-11-07 15:52:41.764316

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '67257dca779e'
down_revision = '4953250f9122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['owner_id'],
                        ['users.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
