"""added notes text field

Revision ID: c207652104e8
Revises: 67257dca779e
Create Date: 2017-11-07 17:03:51.334433

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c207652104e8'
down_revision = '67257dca779e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('text', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'text')
    # ### end Alembic commands ###
